### ISSUE TITLE
Publish protoc-gen-go-aip as a GitHub Release

### ISSUE THREAD

**Issue by goober** [einride/aip-go#213]
To be able to use the go-aip plugin for protoc it is currently required to build it from source. 
It would be preferable to be able to download a pre-compiled binary from GitHub directly. i.e. publish the binaries together with the GitHub Release.

Is that something that you have considered or do you have another recommendation than compiling from source?

**Comment by ericwenn** [comment]
Hello, the generated code has dependencies on the release library (similar to grpc-go).
This means you want to use the generator which matches your installed version of aip-go.

The easiest way to ensure this is to build the binary using the version in modfile.

**Comment by goober** [comment]
Thanks, that make sense. I close this issue.
